### ISSUE TITLE
OSCClientError: while sending: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by tdhooper** [trevorvanhoof/sqrmelon#4]
Trying to get this working on Ubuntu. When started I get this OSCClientError. If I comment out the `send` calls the tool loads.

Full error:
```
Traceback (most recent call last):
  File "__init__.py", line 469, in <module>
    run()
  File "__init__.py", line 460, in run
    win = App()
  File "__init__.py", line 70, in __init__
    self._timer = Timer()
  File "/home/tdhooper/Projects/sqrmelon/SqrMelon/timeslider.py", line 92, in __init__
    self.projectOpened()
  File "/home/tdhooper/Projects/sqrmelon/SqrMelon/timeslider.py", line 155, in projectOpened
    self.end = min(endTime, self.maxTime)
  File "/home/tdhooper/Projects/sqrmelon/SqrMelon/timeslider.py", line 263, in end
    self.endChanged.emit(value)
  File "/home/tdhooper/Projects/sqrmelon/SqrMelon/qtutil.py", line 131, in emit
    self.__connections[i](*args, **kwargs)
  File "/home/tdhooper/Projects/sqrmelon/SqrMelon/timeslider.py", line 101, in __oscSetLoopRange
    self.__osc.loop(self.__start, self.__end)
  File "/home/tdhooper/Projects/sqrmelon/SqrMelon/timeslider.py", line 66, in loop
    self.__client.send(msg)
  File "/home/tdhooper/.local/lib/python2.7/site-packages/OSC.py", line 1141, in send
    raise OSCClientError("while sending: %s" % str(e))
OSCClientError: while sending: [Errno 111] Connection refused
```

**Comment by trevorvanhoof** [comment]
Cool that it works that far!

Ihardcoded the OSCClient to connect to localhost:2223 (timslider.py ln 20) and push BPM and play/pause to ableton.

I've just pushed a simple change that catches OSCClientErrors and silently ignores them when sending. 

To do this properly in the future I'd have to dive into sockets and why the arbitrary connection doesn't raise errors when there's no receiving socket.

**Comment by tdhooper** [comment]
That fixes it, thank you :)
